name: voicebook
description: Voice-first book editor for Android and Web built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  dio: ^5.4.2+1
  web_socket_channel: ^3.0.1
  flutter_quill: ^9.3.5
  record: ^5.0.5
  just_audio: ^0.9.36
  flutter_treeview: ^1.0.7
  drag_and_drop_lists: ^0.3.6
  reorderables: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_web: ^1.1.0
  intl: ^0.19.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/icons/
