name: voicebook
description: Voice-first book editor for Android and Web built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.4
  flutter_riverpod: ^2.5.1
  dio: ^5.4.2+1
  web_socket_channel: ^3.0.1
  flutter_quill: ^11.4.2
  record: ^6.1.1
  just_audio: ^0.10.5
  drag_and_drop_lists: ^0.4.2
  reorderables: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/icons/
